services:
  backend:
    image: ${DOCKERHUB_USERNAME:-ptxuan}/bookora-api:latest
    container_name: nestjs-backend
    restart: always
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio-storage
    restart: always
    command: server /data --console-address ":9001"
    env_file:
      - .env.production
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  postgres_data:
  minio_data:
